Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy import integrate
help(integrate.quad)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-33-8681296cbca3>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0mscipy[0m [0;32mimport[0m [0mintegrate[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mhelp[0m[0;34m([0m[0mintegrate[0m[0;34m.[0m[0mquad[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.9.0/x64/lib/python3.9/site-packages/scipy/__init__.py[0m in [0;36m<module>[0;34m[0m
[1;32m     59[0m [0m__all__[0m [0;34m=[0m [0;34m[[0m[0;34m'test'[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m     60[0m [0;34m[0m[0m
[0;32m---> 61[0;31m [0;32mfrom[0m [0mnumpy[0m [0;32mimport[0m [0mshow_config[0m [0;32mas[0m [0mshow_numpy_config[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     62[0m [0;32mif[0m [0mshow_numpy_config[0m [0;32mis[0m [0;32mNone[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     63[0m     raise ImportError(

[0;31mModuleNotFoundError[0m: No module named 'numpy'
ModuleNotFoundError: No module named 'numpy'

